
env: "paper"

kalshi:
  api_key: "a3f90940-0fa7-4fe6-b331-91664f96bdbb"
  private_key: "YOUR_KALSHI_PRIVATE_KEY"
  base_url: "MIIEpAIBAAKCAQEAydP2gg/SSEgM8VsdVCE5Tu+CaVejzyjuvlc7N01h1LZ4TzUn
oqBAnGD3eXD5Ps1OhBJ7vyRj0SLtOP4RrUPQNatqzzBoHSB1ekqFNckP55qN1MM4
NAIfKh451QwwANtDO0FWxrGpSkbZhL/aRxqCUtnlGHwR3YnZpHNK++7Yp72MY4bG
PImMd6yxiO0OY/+JpJk2Fy75MkKAQd1qfikTv5D3TTy/CbICLA36E6/ZOU06sSWd
MdHuVGu/htTErQnxbjwiDSPIX4REVQsFk3cpUDugm4iVv6rKXhglVNhKTKV/b1nY
KPlrwlyuLq8dRRT5w/bVdugsEWRWkxTxTI6yOQIDAQABAoIBAFeK14kpqKnOisKj
pVCJCq0I6VWc/IIOPKQV/SrrJyyXKw8cPMFm5i+ORbmIvau2bMCPrdpGQ/+COUg3
t94iJG0rGayd0AMWQa6WJTqjqADrAmsPdFDmvLLNooMdArNUZ9CLckLD6+y6V34j
o1+lCXM7bQoWQr+Hm/4fPh6RxqrWoOyFIfl2x4nHUp24C96ISrUN1UU3r6GQwEKB
ZC/1IEg0KuB79aMl+gdp1C1QQjJbKcN3Y0rr6KwenEacKI1q1AL1U6ZfDceVjhTw
abb2ANRUXgacm0XLn6CFFlPQ5V+xlaJBPOwp9ZQTawga1U60Id4Rb86oYoQ4bRaM
qrWdxVsCgYEA2XCCQF9ijmq/AmIxJ8xYR9lqYdkmAzbK4alPj0hKK/afTdWVG3sc
+1qQivgfu5s8DkMO47Iv3sUiDSM+QxQQ8b2x7OMibJwGzFmcaisI+yFi0sRLZOE7
ANlqJHv+4JIC36XKqSqXQAzk/eH1XKzCD3gl2OjNXA+LxQndaSvRqusCgYEA7Z61
4X7tlxQ6k10oij0JZzx3DBYKickoeFwn+lAbH85qV4X5sEWilUVr4Gp2WbBWHGhj
Bd0sWea/nkAVZ2GezGwUhBVmAlO0PoalfH4Yme7XfGzToud6s+hpQ6pkNhuQU4Bs
4kL8PgRgFpvJpeyit+qkbptQeKfZJF+1GsmQRmsCgYEAjwEdyPRyvzOZWBn4NjKA
xRBKlPvZsjdxCyTtPFDQ50UV1Hzpyd8YWn9fnOY/CIW5469atYnVTe/cy0MoiblC
w5p80E05sLCVEATHiFOxXmjAs9mBtGElCxPyaPhb0pp05V4GgWePfgJ9ADSByGee
YcolKhlCJo/a3sX0Jl05Ue0CgYBJWx27J3whj9UleTTyuDUW8cuup39JWhhsT8bn
t6MoBok9y9ZxXI38lxnehf9TYOS0kGVBgi4W8u1k5VO2PqTPZu5OeGyteznBs7+S
1zqxCtLrTo1nVR7EO5ODmC6npYrAvHzgvN0yKBeh4yY1WwBA1uc8XiZRmT+nwwQd
6OvpUQKBgQDWxz2CO2/tKe9Bb5IKOB88+fYvsMGSxNaEczIk+QefcVmO4n8lfvAX
2JYwkFEz2+uffi31UQzhwLnbZchbw9LGtsf8GPjFeV7xpuYZGHA+P++zXrSLTBFQ
5EofxIbnzs1X3vrmFwZVEYMrO+jYpypvpEV8v/vMvjAWiwDnLz1giQ=="

polymarket:
  base_url: "https://api.polymarket.com"

strategy:
  min_edge: 0.30
  max_edge: 0.51
  max_notional_per_market: 100.0
  max_daily_loss: 200.0

backtest:
  start_date: "2024-01-01"
  end_date: "2024-12-31"

dashboard:
  host: "0.0.0.0"
  port: 8000
